name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/zida01/kubernetes-cicd-tutorial:latest
            ghcr.io/zida01/kubernetes-cicd-tutorial:${{ github.sha }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials

          rm -rf gitops
          git clone https://github.com/Zida01/grade-api-gitops.git gitops
          cd gitops

          sed -i "s|image: ghcr.io/zida01/kubernetes-cicd-tutorial:.*|image: ghcr.io/zida01/kubernetes-cicd-tutorial:${{ github.sha }}|g" deployment.yaml

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes"
          git push -f https://${GIT_TOKEN}@github.com/Zida01/grade-api-gitops.git main # OK
